# Generated by Django 5.2.1 on 2025-06-14 22:19

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(max_length=50, verbose_name=django.contrib.auth.models.User),
        ),
    ]
