# Generated by Django 5.2.1 on 2025-06-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0005_alter_categoria_options_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(max_length=50, verbose_name='Nome do cliente'),
        ),
    ]
